// Generated by CoffeeScript 1.6.2
var CheckQuestionService,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

exports.CheckQuestionService = CheckQuestionService = (function() {
  function CheckQuestionService(app, node_modules, database, req, res, next) {
    this.app = app;
    this.node_modules = node_modules;
    this.database = database;
    this.req = req;
    this.res = res;
    this.next = next;
    this.sendHtml = __bind(this.sendHtml, this);
    this.buildHtml = __bind(this.buildHtml, this);
    this.checkQuestions = __bind(this.checkQuestions, this);
    this.getCheckList = __bind(this.getCheckList, this);
    this.searchEvent = __bind(this.searchEvent, this);
    this.results = this.req.body.results;
    this.categoryTable = this.database.categoryTable;
    this.eventTable = this.database.eventTable;
    this.checkTable = this.database.checkTable;
    this.async = this.node_modules.async;
    this.eventDatas = "";
    this.checkLists = [];
    this.recommend = [];
    this.html = "";
  }

  CheckQuestionService.prototype.exec = function() {
    return this.async.series([this.searchEvent, this.getCheckList, this.checkQuestions, this.buildHtml, this.sendHtml], function(err, result) {
      if (err) {
        throw err;
        res.redirect('/');
      }
      return console.log("all done. " + result);
    });
  };

  CheckQuestionService.prototype.searchEvent = function(callBack) {
    var _this = this;

    return this.eventTable.findAll().success(function(columns) {
      var i, _i, _ref;

      _this.eventDatas = columns;
      for (i = _i = 0, _ref = _this.eventDatas.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
        _this.checkLists[i] = new Array();
      }
      return callBack(null, 1);
    }).error(function(err) {
      return console.log("eventTable searchEventMethod err > " + err);
    });
  };

  CheckQuestionService.prototype.getCheckList = function(callBack) {
    var _this = this;

    return this.checkTable.findAll().success(function(columns) {
      var column, _i, _len;

      for (_i = 0, _len = columns.length; _i < _len; _i++) {
        column = columns[_i];
        if (column.flag) {
          _this.checkLists[column.eventID - 1].push({
            categoryID: "" + column.categoryID,
            flag: "true"
          });
        } else {
          _this.checkLists[column.eventID - 1].push({
            categoryID: "" + column.categoryID,
            flag: "false"
          });
        }
      }
      return callBack(null, 2);
    }).error(function(err) {
      return console.log("checkTable getCheckListMethod err > " + err);
    });
  };

  CheckQuestionService.prototype.checkQuestions = function(callBack) {
    var flag, i, j, _i, _j, _ref, _ref1;

    for (i = _i = 0, _ref = this.eventDatas.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
      flag = true;
      if (this.results.length !== this.checkLists[i].length) {
        continue;
      }
      for (j = _j = 0, _ref1 = this.results.length; 0 <= _ref1 ? _j < _ref1 : _j > _ref1; j = 0 <= _ref1 ? ++_j : --_j) {
        if ((this.results[j].categoryID !== this.checkLists[i][j].categoryID) || (this.results[j].flag !== this.checkLists[i][j].flag)) {
          flag = false;
          break;
        }
      }
      if (flag === true) {
        this.recommend.push(i + 1);
      }
    }
    return callBack(null, 3);
  };

  CheckQuestionService.prototype.buildHtml = function(callBack) {
    var event, i, _i, _j, _len, _ref, _ref1;

    this.html = "";
    _ref = this.eventDatas;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      event = _ref[_i];
      for (i = _j = 0, _ref1 = this.recommend.length; 0 <= _ref1 ? _j < _ref1 : _j > _ref1; i = 0 <= _ref1 ? ++_j : --_j) {
        if (event.eventID === this.recommend[i]) {
          this.html += "<div class=\"qu-content row\">\n  <a href='/result?eventID=" + event.eventID + "'>\n    <div class=\"event-icon_" + i + " col-lg-4\">\n      <img src=\"/images/" + event.eventID + "_icon.png\" alt=\"" + event.name_img + "\"/>\n      <p>" + event.name + "</p>\n    </div>\n  </a>\n</div>";
        }
      }
    }
    return callBack(null, 4);
  };

  CheckQuestionService.prototype.sendHtml = function(callBack) {
    this.res.send(this.html);
    return callBack(null, 5);
  };

  return CheckQuestionService;

})();

/*
//@ sourceMappingURL=CheckQuestionService.map
*/
