// Generated by CoffeeScript 1.6.2
var GetQuestionService,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

exports.GetQuestionService = GetQuestionService = (function() {
  function GetQuestionService(app, node_modules, database, req, res, next) {
    this.app = app;
    this.node_modules = node_modules;
    this.database = database;
    this.req = req;
    this.res = res;
    this.next = next;
    this.sendJson = __bind(this.sendJson, this);
    this.getCategory = __bind(this.getCategory, this);
    this.async = this.node_modules.async;
    this.categoryTable = this.database.categoryTable;
    this.jsons = [];
  }

  GetQuestionService.prototype.exec = function() {
    var _this = this;

    return this.async.series([this.getCategory, this.sendJson], function(err, result) {
      if (err) {
        throw err;
        _this.res.redirect('/');
      }
      return console.log("all done. " + result);
    });
  };

  GetQuestionService.prototype.getCategory = function(callBack) {
    return this.categoryTable.findAll().success(function(columns) {
      var column, i, _i, _len, _results;

      this.jsons = [];
      _results = [];
      for (i = _i = 0, _len = columns.length; _i < _len; i = ++_i) {
        column = columns[i];
        _results.push(this.jsons[i] = {
          id: column.categoryID,
          name: column.categoryName
        });
      }
      return _results;
    }).error(function(err) {
      return console.log("question json error >> " + err);
    });
  };

  GetQuestionService.prototype.sendJson = function(callBack) {
    this.res.send(jsons);
    return callBack(null, 5);
  };

  return GetQuestionService;

})();

/*
//@ sourceMappingURL=GetQuestionService.map
*/
