// Generated by CoffeeScript 1.6.2
var TopPageClass;

exports.TopPageClass = TopPageClass = (function() {
  var _pageName;

  _pageName = 'top';

  function TopPageClass(option) {
    this.option = option;
    this.app = this.option.app;
    this.node_modules = this.option.node_modules;
    this.database = this.option.database;
  }

  TopPageClass.prototype.getTopPage = function() {
    var _this = this;

    return this.app.get('/', function(req, res, next) {
      return res.render(_pageName);
    });
  };

  return TopPageClass;

})();

/*
//@ sourceMappingURL=TopPageController.map
*/
