// Generated by CoffeeScript 1.6.2
module.exports = function(option) {
  var QuestionController, ResultController, SportsListController, TopController, questionPageController, resultPageController, sportslistPageController, topPageController;

  this.app = option.app;
  this.database = option.database;
  this.node_modules = option.node_modules;
  TopController = require('./Top/TopPageController');
  topPageController = new TopController.TopPageClass(option);
  topPageController.getTopPage();
  QuestionController = require('./Question/QuestionPageController');
  questionPageController = new QuestionController.QuestionPageClass(option);
  questionPageController.getQuestionPage();
  questionPageController.getQuestionJson();
  questionPageController.submitQuestion();
  SportsListController = require('./SportsList/SportsListController');
  sportslistPageController = new SportsListController.SportsListPageClass(option);
  sportslistPageController.getSportsListPage();
  QuestionController = require('./Question/QuestionPageController');
  questionPageController = new QuestionController.QuestionPageClass(option);
  questionPageController.getQuestionPage();
  questionPageController.getQuestionJson();
  ResultController = require('./Result/ResultPageController');
  resultPageController = new ResultController.ResultPageClass(option);
  resultPageController.getResultPage();
  return console.log("controller is setup");
};

/*
//@ sourceMappingURL=controller.map
*/
