// Generated by CoffeeScript 1.6.3
module.exports = function(options) {
  var Database, columns, config, dbname, dbpass, dbuser, hostname, portnum, seq, seq_option, sequelize;
  config = options.config.database;
  sequelize = options.node_modules.sequelize;
  dbname = config.dbname;
  dbuser = config.dbuser;
  dbpass = config.server_pass;
  hostname = config.hostname;
  portnum = config.port;
  seq = new sequelize(dbname, dbuser, dbpass, {
    host: hostname,
    port: portnum
  });
  Database = {};
  columns = {};
  seq_option = {
    timestamps: false,
    freezeTableName: true
  };
  Database.seq = seq;
  columns.eventTable = {
    eventID: {
      type: sequelize.INTEGER,
      primaryKey: true
    },
    name: sequelize.STRING,
    introduction: sequelize.TEXT,
    point: sequelize.TEXT
  };
  Database.eventTable = seq.define("event_table", columns.eventTable, seq_option);
  columns.categoryTable = {
    categoryID: {
      type: sequelize.INTEGER,
      primaryKey: true
    },
    categoryName: sequelize.STRING
  };
  Database.categoryTable = seq.define("category_table", columns.categoryTable, seq_option);
  columns.checkTable = {
    eventID: {
      type: sequelize.INTEGER,
      primaryKey: true
    },
    categoryID: {
      type: sequelize.INTEGER,
      primaryKey: true
    },
    flag: sequelize.BOOLEAN
  };
  Database.checkTable = seq.define("check_table", columns.checkTable, seq_option);
  columns.movieTable = {
    eventID: {
      type: sequelize.INTEGER,
      primaryKey: true
    },
    movieID: {
      type: sequelize.INTEGER,
      primaryKey: true
    },
    url: sequelize.TEXT
  };
  Database.movieTable = seq.define("movie_table", columns.movieTable, seq_option);
  console.log('Database is setup.');
  return Database;
};

/*
//@ sourceMappingURL=database.map
*/
