// Generated by CoffeeScript 1.6.2
var SportsListPageClass;

exports.SportsListPageClass = SportsListPageClass = (function() {
  var _pageName;

  _pageName = 'sportslist';

  function SportsListPageClass(option) {
    this.option = option;
    this.app = this.option.app;
    this.node_modules = this.option.node_modules;
    this.database = this.option.database;
  }

  SportsListPageClass.prototype.getSportsListPage = function() {
    var _this = this;

    return this.app.get('/sportslist', function(req, res, next) {
      return res.render(_pageName);
    });
  };

  return SportsListPageClass;

})();

/*
//@ sourceMappingURL=SportsListController.map
*/
