// Generated by CoffeeScript 1.6.2
var AppClass;

exports.AppClass = AppClass = (function() {
  var _dir, _engine, _keepExtention, _port;

  _keepExtention = true;

  _engine = "ejs";

  _port = 3000;

  _dir = "" + __dirname + "/../../";

  function AppClass() {
    this.port = _port;
    this.tmpDir = "" + _dir + "tmp";
    this.view = "" + _dir + "views";
    this["public"] = "" + _dir + "public";
    this.routes = "" + _dir + "routse";
    this.favicon = "" + this["public"] + "/images/favicon.ico";
  }

  AppClass.prototype.getPort = function() {
    return this.port;
  };

  AppClass.prototype.getView = function() {
    return this.view;
  };

  AppClass.prototype.getPublic = function() {
    return this["public"];
  };

  AppClass.prototype.getRoutes = function() {
    return this.routes;
  };

  AppClass.prototype.getEngine = function() {
    return _engine;
  };

  AppClass.prototype.getFavicon = function() {
    return this.favicon;
  };

  AppClass.prototype.upload = function() {
    return {
      uploadDir: this.tmpDir,
      isKeepExtensions: _keepExtention
    };
  };

  AppClass.prototype.compress = function() {
    return {
      level: 9,
      memLevel: 9
    };
  };

  return AppClass;

})();

/*
//@ sourceMappingURL=AppClass.map
*/
