// Generated by CoffeeScript 1.6.2
var LogClass;

exports.LogClass = LogClass = (function() {
  var _date, _dir, _size;

  function LogClass() {}

  _dir = "" + __dirname + "/../../logs";

  _size = 1024 * 1024;

  _date = '-yyyy-MM-dd';

  LogClass.prototype.constructer = function() {};

  LogClass.prototype.getName = function() {
    return "" + _dir + "/log";
  };

  LogClass.prototype.getSize = function() {
    return _size;
  };

  LogClass.prototype.getStdout = function() {
    return false;
  };

  LogClass.prototype.getPattern = function() {
    return _date;
  };

  LogClass.prototype.settings = function() {
    return {
      appenders: [
        {
          'type': 'console'
        }, {
          'type': 'file',
          'filename': this.getName(),
          'maxLogSize': this.getSize(),
          'pattern': this.getPattern(),
          'category': 'console'
        }
      ],
      replaceConsole: this.getStdout()
    };
  };

  LogClass.prototype.connect = function() {
    return {
      nolog: ['\\.css', '\\.js', '\\.gif', '\\.jpg', '\\.png'],
      format: JSON.stringify({
        'method': ':method',
        'request': ':url',
        'status': ':status'
      })
    };
  };

  return LogClass;

})();

/*
//@ sourceMappingURL=LogClass.map
*/
